[project]
name = "aoc24"
version = "0.1.0"
description = "My Advent of Code attempts for 2024."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = ["pytest>=8.3.3"]

[tool.pytest.ini_options]
pythonpath = "src"
